version: '3.8'

services:
  egress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agora-egress
    restart: unless-stopped
    ports:
      - "8080:8080"  # API port
      - "8182:8182"  # Health check port
      - "3000:3000"  # Template server port
    volumes:
      - ./config:/etc/egress/config
      - ./recordings:/recordings
    environment:
      - TZ=UTC
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8182/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
