# Persistent Volumes for recordings and snapshots
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recordings-pvc
  namespace: rtc-egress
spec:
  accessModes:
    - ReadWriteMany  # Shared across multiple egress pods
  resources:
    requests:
      storage: 100Gi
  storageClassName: fast-ssd  # Adjust to your storage class
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshots-pvc
  namespace: rtc-egress
spec:
  accessModes:
    - ReadWriteMany  # Shared across multiple egress pods
  resources:
    requests:
      storage: 50Gi
  storageClassName: fast-ssd  # Adjust to your storage class