name: Build and Push Debug Docker Images

on:
  workflow_dispatch:
    inputs:
      services:
        description: 'Services to build (comma-separated: api_server,egress,flexible_recorder,uploader,webhook_notifier,monolithic or "all")'
        required: true
        default: 'all'
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compute build version
      run: |
        BASE_VERSION=$(python3 -c "import pathlib,re;text=pathlib.Path('pkg/version/version.go').read_text();m=re.search(r'Version\\s*=\\s*\"v([^\"\\n]+)\"', text);print(m.group(1) if m else '0.0.0')")
        if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
          RAW_VERSION="${GITHUB_REF#refs/tags/v}"
          echo "VERSION_OVERRIDE=v${RAW_VERSION}" >> "$GITHUB_ENV"
        else
          DATE=$(date -u +%Y%m%d)
          SHORT_SHA=${GITHUB_SHA::7}
          SEMVER_VERSION="${BASE_VERSION}-${DATE}+${SHORT_SHA}"
          echo "VERSION_OVERRIDE=v${SEMVER_VERSION}" >> "$GITHUB_ENV"
        fi

    - name: Build binaries in Docker
      run: |
        # Build using the builder stage from Dockerfile.debug
        docker build --platform linux/amd64 --target builder -t temp-builder -f Dockerfile.debug \
          --build-arg AGORA_SDK_URL=https://download.agora.io/rtsasdk/release/Agora-RTC-x86_64-linux-gnu-v4.4.32-20250425_144419-675648.tgz \
          .

        # Extract built binaries and SDK from the container
        docker run --rm -v $PWD:/output temp-builder \
          bash -c "cp -r /build/bin /output/ && cp -r /build/agora_sdk /output/"

    - name: Upload binaries as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: |
          bin/
          agora_sdk/
        retention-days: 1

  build-service-debug-images:
    needs: build-binaries
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        service: [api_server, egress, flexible_recorder, uploader, webhook_notifier]
        include:
          - service: api_server
            image_name: api-server
          - service: egress
            image_name: egress
          - service: flexible_recorder
            image_name: flexible-recorder
          - service: uploader
            image_name: uploader
          - service: webhook_notifier
            image_name: webhook-notifier

    steps:
    - name: Check if service should be built
      id: should_build
      run: |
        SERVICES="${{ github.event.inputs.services }}"
        SERVICE="${{ matrix.service }}"
        if [[ "$SERVICES" == "all" ]] || [[ "$SERVICES" == *"$SERVICE"* ]]; then
          echo "build=true" >> $GITHUB_OUTPUT
        else
          echo "build=false" >> $GITHUB_OUTPUT
        fi

    - name: Checkout repository
      if: steps.should_build.outputs.build == 'true'
      uses: actions/checkout@v4

    - name: Download binaries
      if: steps.should_build.outputs.build == 'true'
      uses: actions/download-artifact@v4
      with:
        name: binaries

    - name: Set up Docker Buildx
      if: steps.should_build.outputs.build == 'true'
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      if: steps.should_build.outputs.build == 'true'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Compute image tags
      if: steps.should_build.outputs.build == 'true'
      run: |
        IMAGE_NAME="${{ matrix.image_name }}"
        REPO=$(echo "${{ env.REGISTRY }}/${{ github.repository }}/${IMAGE_NAME}" | tr '[:upper:]' '[:lower:]')
        if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
          echo "EXTRA_IMAGE_TAG=" >> "$GITHUB_ENV"
          echo "BRANCH_IMAGE_TAG=" >> "$GITHUB_ENV"
        else
          BASE_VERSION=$(python3 -c "import pathlib,re;text=pathlib.Path('pkg/version/version.go').read_text();m=re.search(r'Version\\s*=\\s*\"v([^\"\\n]+)\"', text);print(m.group(1) if m else '0.0.0')")
          DATE=$(date -u +%Y%m%d)
          SHORT_SHA=${GITHUB_SHA::7}
          SEMVER_VERSION="${BASE_VERSION}-${DATE}+${SHORT_SHA}"
          SAFE_VERSION=${SEMVER_VERSION//+/-}
          SAFE_BRANCH=$(echo "${GITHUB_REF_NAME}" | tr '/' '-')
          echo "EXTRA_IMAGE_TAG=${REPO}:${SAFE_VERSION}-debug" >> "$GITHUB_ENV"
          echo "BRANCH_IMAGE_TAG=${REPO}:${SAFE_BRANCH}-debug" >> "$GITHUB_ENV"
        fi

    - name: Extract metadata
      if: steps.should_build.outputs.build == 'true'
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.image_name }}
        tags: |
          type=ref,event=branch,suffix=-debug
          type=ref,event=pr,suffix=-debug
          type=semver,pattern={{version}},suffix=-debug
          type=semver,pattern={{major}}.{{minor}},suffix=-debug
          type=sha,format=short,suffix=-debug
          type=raw,value=debug,enable={{is_default_branch}}

    - name: Build and push service debug Docker image
      if: steps.should_build.outputs.build == 'true'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: cmd/${{ matrix.service }}/Dockerfile.debug
        platforms: linux/amd64
        push: true
        tags: |
          ${{ steps.meta.outputs.tags }}
          ${{ env.EXTRA_IMAGE_TAG != '' && env.EXTRA_IMAGE_TAG || '' }}
          ${{ env.BRANCH_IMAGE_TAG != '' && env.BRANCH_IMAGE_TAG || '' }}
        labels: ${{ steps.meta.outputs.labels }}
        provenance: false
        sbom: false

  build-monolithic-debug-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check if monolithic should be built
      id: should_build
      run: |
        SERVICES="${{ github.event.inputs.services }}"
        if [[ "$SERVICES" == "all" ]] || [[ "$SERVICES" == *"monolithic"* ]]; then
          echo "build=true" >> $GITHUB_OUTPUT
        else
          echo "build=false" >> $GITHUB_OUTPUT
        fi

    - name: Checkout repository
      if: steps.should_build.outputs.build == 'true'
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      if: steps.should_build.outputs.build == 'true'
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      if: steps.should_build.outputs.build == 'true'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Compute image tags
      if: steps.should_build.outputs.build == 'true'
      run: |
        REPO=$(echo "${{ env.REGISTRY }}/${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
          echo "EXTRA_IMAGE_TAG=" >> "$GITHUB_ENV"
          echo "BRANCH_IMAGE_TAG=" >> "$GITHUB_ENV"
        else
          BASE_VERSION=$(python3 -c "import pathlib,re;text=pathlib.Path('pkg/version/version.go').read_text();m=re.search(r'Version\\s*=\\s*\"v([^\"\\n]+)\"', text);print(m.group(1) if m else '0.0.0')")
          DATE=$(date -u +%Y%m%d)
          SHORT_SHA=${GITHUB_SHA::7}
          SEMVER_VERSION="${BASE_VERSION}-${DATE}+${SHORT_SHA}"
          SAFE_VERSION=${SEMVER_VERSION//+/-}
          SAFE_BRANCH=$(echo "${GITHUB_REF_NAME}" | tr '/' '-')
          echo "EXTRA_IMAGE_TAG=${REPO}:${SAFE_VERSION}-debug" >> "$GITHUB_ENV"
          echo "BRANCH_IMAGE_TAG=${REPO}:${SAFE_BRANCH}-debug" >> "$GITHUB_ENV"
        fi

    - name: Extract metadata
      if: steps.should_build.outputs.build == 'true'
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}
        tags: |
          type=ref,event=branch,suffix=-debug
          type=ref,event=pr,suffix=-debug
          type=semver,pattern={{version}},suffix=-debug
          type=semver,pattern={{major}}.{{minor}},suffix=-debug
          type=sha,format=short,suffix=-debug
          type=raw,value=debug,enable={{is_default_branch}}

    - name: Build and push monolithic debug Docker image
      if: steps.should_build.outputs.build == 'true'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.debug
        platforms: linux/amd64
        push: true
        tags: |
          ${{ steps.meta.outputs.tags }}
          ${{ env.EXTRA_IMAGE_TAG != '' && env.EXTRA_IMAGE_TAG || '' }}
          ${{ env.BRANCH_IMAGE_TAG != '' && env.BRANCH_IMAGE_TAG || '' }}
        labels: ${{ steps.meta.outputs.labels }}
        provenance: false
        sbom: false
        build-args: |
          AGORA_SDK_URL=https://download.agora.io/rtsasdk/release/Agora-RTC-x86_64-linux-gnu-v4.4.32-20250425_144419-675648.tgz
